import {
  Link2, Type, Mail, Phone, MessageSquare, Contact, Wifi,
  Calendar, Bitcoin, Music, Video, FileText, Share2, Smartphone,
  Images, Star, MessageCircle, MapPin, Globe, CreditCard,
} from "lucide-react";

export const QR_TABS = [
  { id: "url", icon: Link2, label: "URL", category: "essential",
    description: "Link to any website" },
  { id: "text", icon: Type, label: "Text", category: "essential",
    description: "Plain text message" },
  { id: "email", icon: Mail, label: "Email", category: "essential",
    description: "Pre-filled email composer" },
  { id: "phone", icon: Phone, label: "Phone", category: "essential",
    description: "One-tap phone number" },
  { id: "sms", icon: MessageSquare, label: "SMS", category: "essential",
    description: "Pre-filled text message" },
  { id: "wifi", icon: Wifi, label: "WiFi", category: "essential",
    description: "Auto-connect to network" },
  { id: "location", icon: MapPin, label: "Location", category: "essential",
    description: "Open in maps app" },
  { id: "vcard", icon: Contact, label: "vCard", category: "contact",
    description: "Save as phone contact" },
  { id: "mecard", icon: CreditCard, label: "meCard", category: "contact",
    description: "Compact contact format" },
  { id: "event", icon: Calendar, label: "Event", category: "contact",
    description: "Add to calendar" },
  { id: "facebook", icon: Globe, label: "Facebook", category: "social",
    description: "Facebook page link" },
  { id: "twitter", icon: MessageCircle, label: "Twitter / X", category: "social",
    description: "X profile or tweet" },
  { id: "youtube", icon: Video, label: "YouTube", category: "social",
    description: "YouTube video or channel" },
  { id: "social", icon: Share2, label: "Social Media", category: "social",
    description: "Multi-link landing page" },
  { id: "mp3", icon: Music, label: "MP3 / Audio", category: "media",
    description: "Audio file via cloud upload" },
  { id: "video", icon: Video, label: "Video", category: "media",
    description: "Video file via cloud upload" },
  { id: "pdf", icon: FileText, label: "PDF", category: "media",
    description: "PDF document via cloud upload" },
  { id: "gallery", icon: Images, label: "Image Gallery", category: "media",
    description: "Image showcase" },
  { id: "appstore", icon: Smartphone, label: "App Store", category: "business",
    description: "Smart link to iOS/Android app" },
  { id: "rating", icon: Star, label: "Rating / Reviews", category: "business",
    description: "Collect Google reviews" },
  { id: "feedback", icon: MessageCircle, label: "Feedback Form", category: "business",
    description: "Customer feedback survey" },
  { id: "bitcoin", icon: Bitcoin, label: "Bitcoin", category: "business",
    description: "Crypto payment request" },
];

export const CATEGORIES = [
  { id: "essential", label: "Essential", color: "brand" },
  { id: "contact",   label: "Contact",   color: "accent" },
  { id: "social",    label: "Social",    color: "brand" },
  { id: "media",     label: "Media",     color: "accent" },
  { id: "business",  label: "Business",  color: "brand" },
];
