export const QR_TEMPLATES = [
  { id: "classic", name: "Classic", settings: {
    dotPattern: "square", cornerStyle: "square", eyeBallStyle: "square",
    fgColor: "#000000", bgColor: "#ffffff", useGradient: false,
    frameStyle: "none", useCustomEyeColor: false,
  }},
  { id: "sunset", name: "Sunset", settings: {
    dotPattern: "rounded", cornerStyle: "dot", eyeBallStyle: "dot",
    useGradient: true, gradientColor1: "#F97316", gradientColor2: "#EC4899",
    gradientType: "linear", bgColor: "#ffffff", frameStyle: "none",
    useCustomEyeColor: false,
  }},
  { id: "ocean", name: "Ocean", settings: {
    dotPattern: "classy", cornerStyle: "extra-rounded", eyeBallStyle: "dot",
    useGradient: true, gradientColor1: "#2563EB", gradientColor2: "#06B6D4",
    gradientType: "linear", bgColor: "#ffffff", frameStyle: "none",
    useCustomEyeColor: false,
  }},
  { id: "mono-bold", name: "Mono Bold", settings: {
    dotPattern: "square", cornerStyle: "square", eyeBallStyle: "square",
    fgColor: "#000000", bgColor: "#ffffff", useGradient: false,
    frameStyle: "banner-bottom", frameText: "SCAN ME",
    frameFillColor: "#000000", frameTextColor: "#FFFFFF",
    useCustomEyeColor: false,
  }},
  { id: "pastel-round", name: "Pastel Round", settings: {
    dotPattern: "rounded", cornerStyle: "extra-rounded", eyeBallStyle: "dot",
    useGradient: true, gradientColor1: "#EC4899", gradientColor2: "#A78BFA",
    gradientType: "linear", bgColor: "#FFF7ED", frameStyle: "none",
    useCustomEyeColor: false,
  }},
  { id: "forest", name: "Forest", settings: {
    dotPattern: "classy", cornerStyle: "extra-rounded", eyeBallStyle: "dot",
    useGradient: true, gradientColor1: "#059669", gradientColor2: "#10B981",
    gradientType: "linear", bgColor: "#ECFDF5", frameStyle: "none",
    useCustomEyeColor: false,
  }},
  { id: "royal", name: "Royal", settings: {
    dotPattern: "dots", cornerStyle: "dot", eyeBallStyle: "dot",
    useGradient: true, gradientColor1: "#7C3AED", gradientColor2: "#4F46E5",
    gradientType: "linear", bgColor: "#ffffff", frameStyle: "none",
    useCustomEyeColor: false,
  }},
  { id: "cyberpunk", name: "Cyberpunk", settings: {
    dotPattern: "square", cornerStyle: "square", eyeBallStyle: "square",
    useGradient: true, gradientColor1: "#EC4899", gradientColor2: "#06B6D4",
    gradientType: "linear", bgColor: "#0F172A",
    frameStyle: "scan-corners", frameFillColor: "#06B6D4",
    useCustomEyeColor: false,
  }},
  { id: "coffee", name: "Coffee", settings: {
    dotPattern: "classy", cornerStyle: "extra-rounded", eyeBallStyle: "dot",
    fgColor: "#78350F", bgColor: "#FEF3C7", useGradient: false,
    frameStyle: "none", useCustomEyeColor: false,
  }},
  { id: "neon-night", name: "Neon Night", settings: {
    dotPattern: "rounded", cornerStyle: "extra-rounded", eyeBallStyle: "dot",
    useGradient: true, gradientColor1: "#06B6D4", gradientColor2: "#22D3EE",
    gradientType: "linear", bgColor: "#0F172A", frameStyle: "none",
    useCustomEyeColor: false,
  }},
  { id: "minimal-grey", name: "Minimal Grey", settings: {
    dotPattern: "square", cornerStyle: "square", eyeBallStyle: "square",
    fgColor: "#6B7280", bgColor: "#F9FAFB", useGradient: false,
    frameStyle: "none", useCustomEyeColor: false,
  }},
  { id: "brand-webiox", name: "Brand Webiox", settings: {
    dotPattern: "classy", cornerStyle: "extra-rounded", eyeBallStyle: "dot",
    useGradient: true, gradientColor1: "#4F46E5", gradientColor2: "#7C3AED",
    gradientType: "linear", bgColor: "#ffffff",
    frameStyle: "rounded-box", frameText: "SCAN",
    frameFillColor: "#4F46E5", frameTextColor: "#FFFFFF",
    useCustomEyeColor: false,
  }},
];
